trigger:
  branches:
    include:
    - master

pr: none

pool:
  vmImage: 'ubuntu-latest'
  
steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '929bb19b-5304-4ae9-90cb-bd43ba7e444b'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.sln'
    configuration: 'Release'
    nobuild: true
    includesource: false
    versioningScheme: 'off'
    buildProperties: 'Version=1.0.$(Build.BuildId)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'