name: Build, Test & Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "Package Version"
        required: true
        default: "1.0.0"

jobs:
  nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run:
          dotnet restore
          # set pr number, if it's a pr build
      - name: set pr build number
        id: PRNUMBER
        if: ${{ github.event_name == 'pull_request' }}
        uses: kkak10/pr-number-action@v1.3
        # set report file and title
      - name: Set Test Title
        run: |
          if ${{ github.event_name == 'pull_request' }}
          then
            echo "title=Test Run for PR #${{steps.PRNUMBER.outputs.pr}} (${{github.run_number}})" >> $GITHUB_ENV
            echo "file_name=TestReport.${{steps.PRNUMBER.outputs.pr}}.${{github.run_number}}.md" >> $GITHUB_ENV
          else
            echo "title=Test Run ${{github.run_number}}" >> $GITHUB_ENV
            echo "file_name=TestReport.${{github.run_number}}.md" >> $GITHUB_ENV
          fi
      - run: dotnet test -c Release -l liquid.md
      - run: dotnet pack -c Release
      - uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: |
            **/*.nupkg
            **/*.snupkg
        # upload report as build artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        if: ${{always()}}
        with:
          name: "Test Run"
          path: ${{github.workspace}}/${{env.file_name}}
        # add report as PR comment (if PR)
      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ${{env.file_name}}
