name: Build, Test & Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "Package Version"
        required: true
        default: "1.0.0"

jobs:
  nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: dotnet restore
      - run: dotnet test --configuration Release --logger GitHubActions ./Tests/LinkedDataProofs.Tests/LinkedDataProofs.Tests.csproj
      - run: dotnet test --configuration Release --logger GitHubActions ./Tests/LinkedDataProofs.Bbs.Tests/LinkedDataProofs.Bbs.Tests.csproj
      - run: dotnet pack -c Release
      - uses: actions/upload-artifact@v2
        with:
          name: nuget
          path: |
            **/*.nupkg
            **/*.snupkg